spring:
  config: 
    activate:
      on-profile:
        dev
  #data:
  #  mongodb:
  #    uri: mongodb://spring:passwoord1234@mongodb:27017/booksonline?authSource=admin

server:
  port: 80
  servlet:
    context-path:
    

baseReviewsUrl: http://review-service:8082
#baseReviewsUrl: http://gateway-service:5555/reviews
#baseReviewsUrl: ${BASE_REVIEWS_URL}
