#!/bin/bash

kubectl config set-context $(kubectl config current-context) --namespace=singapore

kubectl create configmap config-repo-order-service --from-file=config-repo/application.yml --from-file=config-repo/order-service.yml --save-config


