#!/bin/bash

# Print commands to the terminal before execution and stop the script if any error occurs
set -ex

kubectl config set-context $(kubectl config current-context) --namespace=singapore

kubectl create secret generic mongodb-server-credentials \
    --from-literal=MONGO_INITDB_ROOT_USERNAME=spring \
    --from-literal=MONGO_INITDB_ROOT_PASSWORD=password1234 \
    --save-config

kubectl create secret generic mongodb-credentials \
    --from-literal=SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=booksonline \
    --from-literal=SPRING_DATA_MONGODB_USERNAME=spring \
    --from-literal=SPRING_DATA_MONGODB_PASSWORD=password1234 \
    --save-config

set +ex
