#!/bin/bash

kubectl config set-context $(kubectl config current-context) --namespace=singapore

kubectl create configmap config-repo-user-service --from-file=config-repo/application.yml --from-file=config-repo/user-service.yml --save-config


