#!/bin/bash

kubectl config set-context $(kubectl config current-context) --namespace=singapore

kubectl create configmap config-repo-frontend-service --from-file=config-repo/application.yml --from-file=config-repo/frontend-service.yml --save-config


