server:
  port: 80

spring:
  application:
    name: book-service
        
#sator: TENETdefault 
                  
---
# test profile only
spring:
  config:
    activate:
      on-profile:
      - test
      
  data:   
    mongodb:
      #authentication-database: admin
      #username: root
      #password: root
      #database: booksonline
      #host: localhost
      #port: 27017
      uri: mongodb://spring:passwoord1234@localhost:27017/booksonline?authSource=admin
      #uri: mongodb://spring:password1234@localhost:27017/booksonline
      #uri: mongodb://localhost:27017/booksonline
      #host: localhost
      #port: 27017
      #database: product-db
      auto-index-creation: true
      
 


enclume: ENCLUMEtest
sator: SATORtest
arepo: AREPOtest
#management.endpoint.health.show-details: "ALWAYS"
              
server:
  port: 80

logging:
  level:
    root: INFO
    com.dub.spring: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    
