#!/bin/bash

kubectl config set-context $(kubectl config current-context) --namespace=singapore

kubectl create secret generic mongodb-server-credentials --from-literal=MONGO_INITDB_ROOT_USERNAME=spring --from-literal=MONGO_INITDB_ROOT_PASSWORD=passwoord1234 --save-config
